#ifndef DEFINES_H
#define DEFINES_H

#define SCREEN_WIDTH 640		
#define SCREEN_HEIGHT 480	
#define TEXT_CHAR_SIZE 20

#define TETRIS_CLEAR_SCORE 1200
#define MULTI_LINE_CLEAR_SCORE 200
#define SINGLE_LINE_CLEAR_SCORE 100
#define BRICK_DROP_SCORE_RATE 1
#define BRICK_LOCK_SCORE 15

#define BRICK_LEFT_BOUNDRY 0	
#define BRICK_RIGHT_BOUNDRY 9	
#define BRICK_LOWER_BOUNDRY 22
#define BRICK_UPPER_BOUNDRY 3
#define SPRITES_IN_BRICK 4
#define BRICK_FALL_RATE 1
#define NUMBER_OF_BRICK_TYPES 7
#define BRICKS_IN_QUEUE (NUMBER_OF_BRICK_TYPES * 2)
#define LEVEL_MAX 25

#define GB_X_OFFSET 11
#define GB_WIDTH 10
#define GB_HEIGHT 23

#endif